spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  datasource:
#    validation-query: SELECT 1
#    test-on-borrow: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

